data = [
    {'name': 'Instagram', 'follower_count': 687, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 652, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 505, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 421, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 394, 'description': 'Actor and wrestler', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 394, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 376, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 357, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 312, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 303, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 301, 'description': 'Sportswear multinational', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 294, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower_count': 288, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 282, 'description': 'Musician', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 279, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 271, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Jennifer Lopez', 'follower_count': 249, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 229, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Nicki Minaj', 'follower_count': 226, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 219, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 212, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 204, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 179, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 177, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Real Madrid CF', 'follower_count': 173, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Cardi B', 'follower_count': 164, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Demi Lovato', 'follower_count': 153, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 149, 'description': 'Musician', 'country': 'Barbados'},
    {'name': 'Chris Brown', 'follower_count': 144, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Drake', 'follower_count': 143, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Ellen DeGeneres', 'follower_count': 136, 'description': 'Comedian and television host', 'country': 'United States'},
    {'name': 'FC Barcelona', 'follower_count': 136, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Billie Eilish', 'follower_count': 124, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kylian Mbappé', 'follower_count': 123, 'description': 'Footballer', 'country': 'France'},
    {'name': 'UEFA Champions League', 'follower_count': 120, 'description': 'Club football competition', 'country': 'Europe'},
    {'name': 'Gal Gadot', 'follower_count': 108, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Lisa', 'follower_count': 105, 'description': 'Musician', 'country': 'Thailand'},
    {'name': 'Vin Diesel', 'follower_count': 103, 'description': 'Actor', 'country': 'United States'},
    {'name': 'NASA', 'follower_count': 96.8, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Shraddha Kapoor', 'follower_count': 94.2, 'description': 'Actress', 'country': 'India'},
    {'name': 'Narendra Modi', 'follower_count': 92.8, 'description': 'Prime Minister of India', 'country': 'India'},
    {'name': 'Priyanka Chopra', 'follower_count': 92.4, 'description': 'Actress', 'country': 'India'},
    {'name': 'Shakira', 'follower_count': 91.6, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'NBA', 'follower_count': 90, 'description': 'Professional basketball league', 'country': 'United States'},
    {'name': 'Snoop Dogg', 'follower_count': 88.2, 'description': 'Musician', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 88.0, 'description': 'Former footballer', 'country': 'United Kingdom'},
    {'name': 'Dua Lipa', 'follower_count': 87.3, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'Jennie', 'follower_count': 86.9, 'description': 'Musician', 'country': 'South Korea'},
    {'name': 'Alia Bhatt', 'follower_count': 86.2, 'description': 'Actress', 'country': 'India'},
]
